language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -e .[test]
# command to run tests
script:
  - pytest --cov=paranoid_model --cov-report xml:cobertura.xml
  -bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r cobertura.xml
